# Generated by Django 5.2.1 on 2025-06-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250, unique=True)),
                ('nomeclatura', models.CharField(max_length=250, unique=True)),
                ('familia', models.CharField(max_length=250)),
                ('nutricao', models.CharField(max_length=250)),
                ('regiao', models.CharField(max_length=250)),
                ('nativa', models.BooleanField(default=False)),
                ('manejo', models.CharField(max_length=250)),
            ],
        ),
    ]
