# Generated by Django 5.1.6 on 2025-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solicitante', models.CharField(max_length=250)),
                ('data', models.DateTimeField()),
                ('motivo', models.CharField(max_length=250)),
                ('obs', models.CharField(max_length=250)),
                ('aceito', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
