# Generated by Django 5.2.3 on 2025-06-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='obs',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
