# Generated by Django 5.2.1 on 2025-06-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_alter_reserva_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='acao_ensino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=250)),
            ],
        ),
    ]
