# Generated by Django 5.2.4 on 2025-07-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_acao_ensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
