# Generated by Django 5.2.1 on 2025-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_planta_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='obs',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='solicitante',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(default='(00) 00000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(unique=True),
        ),
    ]
