# Generated by Django 5.2.1 on 2025-09-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_rename_obs_reserva_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao_ensino',
            name='aceito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acao_ensino',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(),
        ),
    ]
