# Generated by Django 5.2.1 on 2025-09-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_acao_ensino_aceito_acao_ensino_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoEnsino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=250)),
                ('nome', models.CharField(max_length=250, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('aceito', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='acao_ensino',
        ),
    ]
