# Generated by Django 5.2.1 on 2025-10-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_acaoensino_delete_acao_ensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoensino',
            name='autores',
            field=models.CharField(default='Autor Desconhecido', max_length=250),
        ),
    ]
